### ISSUE TITLE
Considering better configuration method

### ISSUE THREAD

**Issue by lkaybob** [ANLAB-KAIST/rust-dpdk#17]
While `rust-dpdk` could automatically clone DPDK's source, and build it, we need to consider those who have downloaded DPDK's source on their own.

### Considerations
* Why `RUSTFLSAGS` is needed
  * Currently, it's specified in README.md, but it does not catch reader's attention. We could separate the content under **Caveats** header.
  * We could also enhance "first-time-build-error", by attaching the link to the header. (In order to have users understands why this is needed.)
* Does environment variable is really needed?
  * Using `RTE_SDK` and `RTE_TARGET` while build could be fragile, and it could be a barrier to those who are not familiar with DPDK.
  * Therefore, we need to seek better solution than being dependent on environment variable.

### References
[`capsule-rs`](https://github.com/capsule-rs/sandbox/blob/master/scripts/dpdk.sh) uses meson/ninja system (But it could be heavyweight solution for us.)

**Comment by leeopop** [comment]
Resolved
