### ISSUE TITLE
Eal Singleton 관리 주체

### ISSUE THREAD

**Issue by leeopop** [ANLAB-KAIST/rust-dpdk#21]
Eal은 복사본이 다른곳에 존재할 수 있으며 (토의한 바와 같의 clone으로 하였습니다)
사용자가 새로운 Eal을 만들 수 있는지 여부는 EalInner 가 최종적으로 메모리에서 사라졌나에 영향을 받습니다.
따라서 여전히 EalInner 에 넣어야 한다고 생각합니다.

**Comment by leeopop** [comment]
rte_eal_init 에 자체적으로 singleton 검사 기능이 있습니다만
저희도 그냥 이 기능에 의존하는건 어떨까 제안드려봅니다.

**Comment by jeehoonkang** [comment]
넵 rte_eal_init의 기능을 쓰는게 정석일 것 같습니다  결론내린 것으로 하겠습니다.
