### ISSUE TITLE
advatanges over other "rust-dpdk? libraries?

### ISSUE THREAD

**Issue by jeehoonkang** [ANLAB-KAIST/rust-dpdk#24]
- https://github.com/flier/rust-dpdk
- https://github.com/netsys/netbricks

겉보기에 우리가 reinventing the wheel을 하는 것처럼 보일건데, 그 작업을 하는 이유가 명시적으로 README에 선언되면 좋겠습니다.

**Comment by leeopop** [comment]
1. binding을 만드는 전 과정을 자동화
(헤더파일의 목록을 직접 만들거나, bindgen 산출물을 버전 관리를 한다던가 하는 일 지양)
1. static inline 함수들을 자동적으로 가져오기
1. DPDK의 whole-archive 플래그 관련 문제 해결

이 세가지가 모두 되고 정상 작동하는 라이브러리가 없어서 만들게 되었습니다.

**Comment by jeehoonkang** [comment]
While it's discussed in README (https://github.com/ANLAB-KAIST/rust-dpdk#goals), we probably need a feature matrix (row = libraries, column = features 1, 2, 3) to visualize the advantages of this library.

**Comment by leeopop** [comment]
이론상 잘 되면 너무 좋지만 사실 DPDK스스로도 빌드 과정과 링크 과정이 조금씩 바뀌어서 넓은 범위의 DPDK 버전을 모두 지원하기는 어려울 수 있습니다만 (어렵다 == 시행착오 및 시간이 필요하다 입니다)

1. 앞으로 DPDK 버전업을 할 때 가능한 한 기존 버전을 feature로 선택할 수 있도록 하겠습니다( `clang-sys`의 사례를 참고하겠습니다) https://github.com/KyleMayes/clang-sys#supported-versions
1. 그럼에도 불구하고 현재 상태 또한 다음 DPDK 버전업 때 할 일을 최소화 할 수 있다는 점에서 여전히 의미가 있다고 생각합니다 (운좋으면 숫자만 바꾸면..).

**Comment by jeehoonkang** [comment]
- 최신 버전의 DPDK만 지원하는 걸로 합시다.  우리가 이걸로 장사할거까진 아니니...
- 아 "feature"라고 해서 혼선이 있었던 것 같은데, 근홍님이 위에 쓰신 1., 2., 3. 장점에 대해 discuss하자는 의미였습니다.  딴거는 1/2만 된다던지 2/3만 된다던지 (우리는 1/2/3/ 다 되고)
