### ISSUE TITLE
Publish to crates.io? 

### ISSUE THREAD

**Issue by cameronelliott** [ANLAB-KAIST/rust-dpdk#60]
Hello,  ANLAB-KAIST team and members.

Thank you for building this and releasing it.

I think yours is one of the better recent rust bindings crates. (I am planning on using it)

I think it deserves to be on crates.io. (it may need a new name, though, it may conflict with existing pkgs)

Does anyone on your team support this?

I could provide some help.

Thanks,
Cameron, Seattle

**Comment by leeopop** [comment]
#62
